name: SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH directory and known_hosts file
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        touch ~/.ssh/id_rsa
        touch ~/.ssh/id_rsa.pub
        pwd
    - name: Run SSH command
      run: |
        ssh-keyscan -H ${{ secrets.SSH_PROD_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PROD_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PROD_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        rsync -avz --exclude='node_modules/' --exclude='.git/' /home/runner/work/dosh.osh.gov.ng/dosh.osh.gov.ng/ owoade@${{ secrets.SSH_PROD_HOST }}:~/dosh.osh.gov.ng/
        ssh owoade@${{ secrets.SSH_PROD_HOST }} "cd dosh.osh.gov.ng && docker stop dosh.osh.gov.ng && docker rm dosh.osh.gov.ng && docker rmi -f dosh.osh.gov.ng && docker build -t dosh.osh.gov.ng . && docker run -d --name=dosh.osh.gov.ng -p 3000:3000 dosh.osh.gov.ng"
